import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Initial from '../components/Initial'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ddev Easy cms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Initial />

    
    </div>
  )
}
